"use client";

import { useMemo, useState } from "react";
import { Check, Copy, Download } from "lucide-react";
import { copyText } from "@/lib/copyText";

const GROUPS: { group: string; items: string[] }[] = [
  { group: "UX", items: ["One clear primary action per screen", "Consistent spacing scale and type hierarchy", "Copy is real and human, no placeholder text", "Destructive actions confirm; common actions don't"] },
  { group: "Mobile / responsive", items: ["Works at 375px with no horizontal scroll", "Tap targets ≥ 44px", "Nav and modals usable on small screens", "Images and tables adapt or scroll gracefully"] },
  { group: "Auth", items: ["Logged-out users can't reach protected screens", "Expired/invalid session handled with a clear path", "Refresh mid-flow doesn't lose the user", "Sign-out actually clears state"] },
  { group: "Database", items: ["All writes validated before persisting", "createdAt / updatedAt set on records", "Lists are paginated; no unbounded scans", "No N+1 queries on hot paths"] },
  { group: "Payments", items: ["Webhook signatures verified", "Write paths are idempotent (safe to retry)", "Failed/declined payments handled with messaging", "Prices/totals shown before commitment"] },
  { group: "Error states", items: ["Failed loads show a human message + retry", "Failed submits don't lose user input", "Offline / network errors handled", "No raw stack traces shown to users"] },
  { group: "Loading states", items: ["Skeletons or clear progress, never frozen UI", "Buttons disable while submitting", "Optimistic UI where it makes sense"] },
  { group: "Empty states", items: ["Every list/table has a designed zero-data state", "Empty states teach the next action", "First-run experience reaches the aha moment"] },
  { group: "Accessibility", items: ["Visible focus states; full keyboard operation", "Sufficient color contrast (WCAG AA)", "Images have alt text; inputs have labels", "prefers-reduced-motion respected"] },
  { group: "Performance", items: ["60fps interactions on mid-range mobile", "Images optimized and correctly sized", "No layout shift (CLS) on load", "Bundle reasonable; heavy deps lazy-loaded"] },
  { group: "Security", items: ["No secrets in client-reachable code", "Inputs sanitized; authz checked server-side", "Rate limiting on public endpoints", "Dependencies free of known criticals"] },
  { group: "Analytics", items: ["Key activation events instrumented", "Funnel from landing → signup → aha tracked", "Errors reported to a monitoring tool"] },
  { group: "SEO", items: ["Unique title + meta description per page", "OpenGraph image and tags set", "Sitemap and robots.txt present", "Semantic headings and structured data where useful"] },
  { group: "Launch readiness", items: ["Custom domain + HTTPS configured", "404 and error pages designed", "Legal pages (privacy/terms) present if needed", "A real person tested the full happy path end-to-end"] },
];

export function QaChecklist() {
  const [done, setDone] = useState<Record<string, boolean>>({});
  const [copyStatus, setCopyStatus] = useState<"idle" | "success" | "error">("idle");

  const total = useMemo(() => GROUPS.reduce((n, g) => n + g.items.length, 0), []);
  const checked = Object.values(done).filter(Boolean).length;
  const pct = Math.round((checked / total) * 100);

  function toggle(key: string) {
    setDone((d) => ({ ...d, [key]: !d[key] }));
  }

  function toMarkdown() {
    return [
      "# AI App QA Checklist — TasteLoop",
      `Progress: ${checked}/${total} (${pct}%)`,
      "",
      ...GROUPS.flatMap((g) => [`## ${g.group}`, ...g.items.map((it) => `- [${done[`${g.group}:${it}`] ? "x" : " "}] ${it}`), ""]),
      "Generated by TasteLoop · Open Loop",
    ].join("\n");
  }

  async function copyMd() {
    const ok = await copyText(toMarkdown());
    setCopyStatus(ok ? "success" : "error");
    if (ok) setTimeout(() => setCopyStatus("idle"), 1800);
  }

  function downloadMd() {
    const blob = new Blob([toMarkdown()], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "ai-app-qa-checklist.md"; a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div>
      <div className="sticky top-20 z-10 mb-8 flex items-center gap-4 rounded-2xl border border-line bg-surface/80 p-4 backdrop-blur">
        <div className="flex-1">
          <div className="flex items-center justify-between text-sm">
            <span className="font-medium">{checked} / {total} complete</span>
            <span className="text-white/50">{pct}%</span>
          </div>
          <div
            className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"
            role="progressbar"
            aria-label="Checklist completion"
            aria-valuemin={0}
            aria-valuemax={total}
            aria-valuenow={checked}
            aria-valuetext={`${checked} of ${total} checks complete`}
          >
            <div className="h-full rounded-full bg-gradient-to-r from-accent to-accent2 transition-all" style={{ width: `${pct}%` }} />
          </div>
        </div>
        <button type="button" onClick={copyMd} aria-label={copyStatus === "error" ? "Copy failed. Try again" : "Copy checklist as Markdown"} className="inline-flex items-center gap-1.5 rounded-lg border border-line bg-white/5 px-3 py-1.5 text-xs font-medium transition hover:border-white/30">
          {copyStatus === "success" ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />} {copyStatus === "success" ? "Copied" : copyStatus === "error" ? "Copy failed" : "Copy MD"}
        </button>
        <button type="button" onClick={downloadMd} className="inline-flex items-center gap-1.5 rounded-lg border border-line bg-white/5 px-3 py-1.5 text-xs font-medium transition hover:border-white/30">
          <Download className="h-3.5 w-3.5" /> Export
        </button>
        <span className="sr-only" role="status" aria-live="polite" aria-atomic="true">
          {copyStatus === "success" ? "Checklist copied to the clipboard." : copyStatus === "error" ? "Could not copy the checklist. Use Export to download it instead." : ""}
        </span>
      </div>

      <div className="grid gap-5 sm:grid-cols-2">
        {GROUPS.map((g) => (
          <div key={g.group} className="rounded-2xl border border-line bg-white/[0.02] p-5">
            <h3 className="text-xs font-bold uppercase tracking-widest text-white/50">{g.group}</h3>
            <ul className="mt-3 space-y-2">
              {g.items.map((it) => {
                const key = `${g.group}:${it}`;
                const isDone = !!done[key];
                return (
                  <li key={key}>
                    <button type="button" onClick={() => toggle(key)} aria-pressed={isDone} className="flex w-full items-start gap-2.5 text-left text-sm">
                      <span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border transition ${isDone ? "border-accent2 bg-accent2/20" : "border-white/20"}`}>
                        {isDone && <Check className="h-3 w-3 text-accent2" />}
                      </span>
                      <span className={`leading-relaxed transition ${isDone ? "text-white/35 line-through" : "text-white/75"}`}>{it}</span>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}
