import type { Pattern } from "./types";

export const PATTERNS: Pattern[] = [
  {
    slug: "scroll-word-reveal",
    title: "Scroll-Linked Word Reveal",
    description: "A manifesto where words light up one by one as you scroll — editorial, premium, and impossible to skim past.",
    category: "text-motion",
    difficulty: "Intermediate",
    tags: ["scroll", "typography", "editorial"],
    featured: true,
    updatedAt: "2026-06-16",
    bestFor: "Mission statements, manifestos, and the one section you want every visitor to actually read.",
    avoidWhen: "Dense feature copy or anything users need to scan quickly — reveal-on-scroll fights fast reading.",
    whyItWorks: "Tying opacity to scroll progress turns reading into a deliberate act. The eye follows the lit word, so attention is directed instead of left to wander.",
    uxPrinciple: "Progressive disclosure: reveal meaning at the pace the user controls, never faster than they can absorb.",
    motionPrinciple: "Scrub, not autoplay. Each word eases from 0.15 → 1 opacity as it crosses the viewport center; already-read words stay lit so nothing flickers.",
    visualReference: "A large serif paragraph, dim by default, lighting word-by-word with a faint caret at the active word. Think a teleprompter you scrub.",
    prompts: {
      v0: "Build a Next.js + Tailwind scroll section where a multi-line serif paragraph reveals word-by-word tied to scroll progress. Each word eases from opacity 0.15 to 1 as it passes the viewport center and stays lit. Pin the section while revealing, then release. Large editorial type. prefers-reduced-motion shows full text.",
      agent: "Add a ScrollReveal component using Framer Motion's useScroll + useTransform. Split the paragraph into word spans; map each word's opacity to a scroll-progress range computed from its index. Pin via a sticky wrapper. Keep it a single client component, typed, with a reduced-motion fallback that renders all words at opacity 1.",
      scaffold: "Create a landing section: a big serif statement that reveals each word as the user scrolls, like reading a teleprompter. Calm, editorial, lots of whitespace. Mobile keeps the effect at smaller type.",
      figma: "Design an editorial manifesto section: oversized serif, one statement, generous line height. Prototype a scroll interaction where words fade from faint to solid in reading order. Provide a reduced-motion variant.",
    },
    implementation: [
      "Split copy into word spans; compute each word's reveal range from its index over total words.",
      "Use a sticky/pinned wrapper so the section holds while the reveal plays.",
      "Drive opacity with scroll progress (useScroll + useTransform), not a timer.",
      "Keep read words lit — never re-dim — to avoid flicker.",
    ],
    qa: [
      "Reduced-motion shows the full paragraph at full opacity, no pin.",
      "No layout shift when the section pins/unpins.",
      "Readable on mobile at smaller type; reveal still tracks scroll.",
      "Caret (if used) lands on the active word, not between words.",
    ],
    aiMistakes: [
      "Autoplaying the reveal on a timer instead of binding it to scroll.",
      "Re-dimming earlier words, causing a strobing effect.",
      "Forgetting the reduced-motion fallback, leaving the text permanently dim for some users.",
    ],
    related: ["kinetic-headline-swap", "aurora-mesh-background"],
  },
  {
    slug: "kinetic-headline-swap",
    title: "Kinetic Headline Word-Swap",
    description: "A fixed headline with one word that flips through options on a loop — 'Build something real / fast / yours.'",
    category: "text-motion",
    difficulty: "Starter",
    tags: ["kinetic", "hero", "loop"],
    updatedAt: "2026-06-15",
    bestFor: "Heros that need to say three things at once without three sentences.",
    avoidWhen: "The swapped words aren't genuinely distinct value props — gimmick without substance reads as cheap.",
    whyItWorks: "Motion on a single word draws the eye to your most important claim and lets you A/B messaging in one line.",
    uxPrinciple: "One focal point. The static frame anchors meaning; the moving word carries the variable.",
    motionPrinciple: "3D flip + blur on swap, ~1.8s hold. Pause on tab blur so it isn't burning frames off-screen.",
    visualReference: "Centered headline, one word in an accent color swapping with a vertical flip every couple seconds.",
    prompts: {
      v0: "Build a Next.js + Motion hero: a centered headline where one word swaps every 1.8s with a 3D flip + blur transition (AnimatePresence). Surrounding words stay fixed. Big variable font, one accent color on the swapping word. Pause on tab blur. Reduced-motion: simple crossfade.",
      agent: "Create a RotatingWord client component: array of words, AnimatePresence mode='wait', rotateX flip with blur, 1.8s interval cleared on unmount and paused on visibilitychange. Typed props for the word list and interval.",
      scaffold: "Make a hero headline where one keyword rotates through 'real, fast, yours, shipped' with a smooth flip animation. Keep the rest of the headline static.",
      figma: "Design a hero with a headline whose final word cycles through 4 options. Prototype a flip transition between variants; show all four states as components.",
    },
    implementation: [
      "Hold the layout width so swapping words don't shift surrounding text.",
      "AnimatePresence with mode='wait' for clean enter/exit.",
      "Clear the interval on unmount; pause on document visibility change.",
    ],
    qa: ["No horizontal jump when words of different lengths swap.", "Pauses when the tab is hidden.", "Reduced-motion falls back to a crossfade."],
    aiMistakes: ["Letting width jump between words.", "Leaving the interval running after unmount (memory leak)."],
    related: ["scroll-word-reveal", "magnetic-primary-cta"],
  },
  {
    slug: "aurora-mesh-background",
    title: "Aurora Mesh Background",
    description: "A slow-drifting multi-stop gradient with grain — the 'crafted' alternative to the default AI diagonal.",
    category: "gradient-backgrounds",
    difficulty: "Starter",
    tags: ["gradient", "grain", "ambient"],
    featured: true,
    updatedAt: "2026-06-16",
    bestFor: "Heros and section backdrops that need depth without a busy image.",
    avoidWhen: "Behind dense text or data — movement plus small text hurts readability.",
    whyItWorks: "Slow movement and grain texture signal intention. The same colors, made to drift, read as designed instead of generated.",
    uxPrinciple: "Background is support, not subject. It should add depth and never compete with content.",
    motionPrinciple: "15–20s ease-in-out loop, low amplitude. Add SVG/CSS noise at ~4% opacity so banding disappears and the surface feels physical.",
    visualReference: "A conic/radial gradient mesh slowly breathing behind content, with a faint film grain over everything.",
    prompts: {
      v0: "Build a Next.js + Tailwind hero background: an animated multi-stop conic/radial gradient mesh that drifts slowly over a 20s loop, with an SVG noise overlay at ~4% opacity. Colors: one brand accent plus two analogous tones. Content sits above with strong contrast. Reduced-motion: static gradient.",
      agent: "Add an AuroraBackground component: absolutely-positioned blurred radial gradients animated with CSS keyframes (transform/opacity only) plus a noise layer via a data-URI SVG. Keep it pointer-events-none and GPU-friendly. Provide a reduced-motion static variant.",
      scaffold: "Give the hero a premium animated gradient background that slowly drifts, with subtle grain over it. Not a flat diagonal — soft, living, ambient.",
      figma: "Design a hero background: soft multi-color mesh gradient with grain. Provide light/dark variants and note the slow drift animation for handoff.",
    },
    implementation: [
      "Animate only transform/opacity on blurred gradient blobs (GPU-safe).",
      "Layer noise as a fixed data-URI SVG at low opacity to kill banding.",
      "Keep the layer pointer-events-none and behind content.",
    ],
    qa: ["60fps on a mid-range phone (throttle CPU 4x to check).", "Text contrast passes over the brightest part of the gradient.", "Reduced-motion renders a static gradient."],
    aiMistakes: ["Animating background-position on a huge element (jank).", "Skipping grain, leaving visible color banding.", "Over-saturating so text becomes unreadable."],
    related: ["scroll-word-reveal", "spotlight-dark-hero-pattern"],
  },
  {
    slug: "shared-element-route-morph",
    title: "Shared-Element Route Morph",
    description: "A card that expands into the next page's hero — the transition that makes a web app feel native.",
    category: "transitions",
    difficulty: "Advanced",
    tags: ["transition", "shared-element", "view-transitions"],
    featured: true,
    updatedAt: "2026-06-16",
    bestFor: "Galleries, catalogs, and detail views where continuity tells the user 'this is the same thing, bigger.'",
    avoidWhen: "Unrelated route changes — forcing a morph where there's no shared object is confusing.",
    whyItWorks: "Continuity of object preserves context. The user never loses the thing they tapped, so navigation feels instant and physical.",
    motionPrinciple: "FLIP / layoutId: the source element's rect animates to the destination's. Keep it 300–450ms, ease-out, with an optional overlay wipe.",
    uxPrinciple: "Object permanence. Animate the change, don't cut to it.",
    visualReference: "Tap a grid card; its image grows and slides to become the detail page's hero, reversing on back.",
    prompts: {
      v0: "Build a Next.js App Router two-page flow using Motion layoutId shared-element transitions: a grid of cards; clicking one morphs its image into the detail page's hero (FLIP), reversing on back. Use the View Transitions API where supported, Motion fallback otherwise. No flash of unstyled content. Reduced-motion: instant nav.",
      agent: "Implement shared-element navigation: give the card image and the detail hero the same layoutId, wrap routes so Motion can animate between them, and add a short overlay wipe during navigation. Prefer the View Transitions API when available; fall back to Motion. Handle the back transition and reduced-motion.",
      scaffold: "When a user taps a project card, animate that card smoothly into the next page's big header image, like a native app. Reverse it when they go back.",
      figma: "Prototype a shared-element transition: a gallery thumbnail expands into the detail screen's hero. Show the morph path and timing for engineering.",
    },
    implementation: [
      "Match layoutId between the source thumbnail and destination hero.",
      "Prefer the View Transitions API; fall back to Motion layout animations.",
      "Add a brief overlay wipe to mask any reflow.",
      "Handle the reverse (back) transition explicitly.",
    ],
    qa: ["No flash of unstyled content mid-transition.", "Back navigation reverses cleanly.", "Reduced-motion does an instant, jank-free nav.", "Works when the image isn't yet loaded on the detail page."],
    aiMistakes: ["Mismatched layoutIds, causing the element to jump instead of morph.", "Forgetting the back transition.", "Animating layout on a huge subtree, causing jank."],
    related: ["magnetic-primary-cta", "command-palette-pattern"],
  },
  {
    slug: "magnetic-primary-cta",
    title: "Magnetic Primary CTA",
    description: "The one button that matters gains a subtle magnetic pull and spring — a quality signal users feel before they read.",
    category: "micro-interactions",
    difficulty: "Starter",
    tags: ["hover", "button", "spring"],
    updatedAt: "2026-06-15",
    bestFor: "The single most important action on a page (the primary CTA, the buy button).",
    avoidWhen: "Every button — magnetism everywhere is noise; reserve it for the one action you want clicked.",
    whyItWorks: "A reactive element feels alive and draws the cursor toward the goal action, nudging clicks without a hard sell.",
    uxPrinciple: "Hierarchy through interaction. The most important control should be the most responsive.",
    motionPrinciple: "Translate the button toward the cursor within a small radius using a spring; reset on leave. Cap displacement (~8–12px) so it stays usable.",
    visualReference: "A primary button that leans gently toward your cursor as you approach, settling with a soft spring.",
    prompts: {
      v0: "Build a MagneticButton in Next.js + Motion: on mousemove within the button's bounds, translate it toward the cursor with a spring (cap ~10px) and reset on leave. Disable on touch and reduced-motion. Use it only for the primary CTA.",
      agent: "Create a reusable MagneticButton client component: track pointer offset from center, apply spring-smoothed translate capped at ~10px, reset on pointer leave. Touch + reduced-motion disable the effect. Strongly typed, accessible (real <button>, focus-visible ring).",
      scaffold: "Make the main call-to-action button subtly pull toward the cursor on hover with a springy feel. Only the primary button, not all of them.",
      figma: "Design the primary CTA with a hover state that nudges toward the pointer. Document the spring feel and the max offset.",
    },
    implementation: ["Compute pointer offset from button center; spring-smooth it.", "Cap translation so the button stays easy to click.", "Disable on touch + reduced-motion; keep a visible focus ring."],
    qa: ["Still clickable — the button never runs away from the cursor.", "Keyboard focus ring visible.", "No effect on touch devices."],
    aiMistakes: ["Applying it to every button.", "Uncapped displacement so the button dodges clicks.", "Breaking keyboard focus styles."],
    related: ["kinetic-headline-swap", "copy-with-feedback"],
  },
  {
    slug: "copy-with-feedback",
    title: "Copy Button with Honest Feedback",
    description: "A copy action that confirms instantly and resets — the smallest interaction that makes a tool feel trustworthy.",
    category: "micro-interactions",
    difficulty: "Starter",
    tags: ["clipboard", "feedback", "tooling"],
    updatedAt: "2026-06-14",
    bestFor: "Any developer tool, prompt library, or code/snippet surface.",
    avoidWhen: "Never — but don't over-animate it; a quick check is enough.",
    whyItWorks: "Immediate, truthful feedback closes the action loop. The user knows it worked without checking elsewhere.",
    uxPrinciple: "Every action needs a reaction. Confirm success at the point of action, then quietly reset.",
    visualReference: "A copy icon that swaps to a green check for ~1.8s, then returns.",
    prompts: {
      v0: "Build a CopyButton in Next.js: writes text to the clipboard, swaps icon to a check with the label 'Copied' for 1.8s, then resets. Handle the clipboard rejection case gracefully. Accessible button with aria-live feedback.",
      agent: "Create a typed CopyButton client component using navigator.clipboard with a try/catch, a transient 'copied' state on a timeout cleared on unmount, and aria-live='polite' so screen readers announce success.",
      scaffold: "Add copy buttons to all code/prompt blocks that show a checkmark and 'Copied' for a moment when clicked.",
      figma: "Design copy-button default, hover, and copied states. Note the ~1.8s confirmation then reset.",
    },
    implementation: ["Use navigator.clipboard with a try/catch fallback.", "Transient copied state via timeout cleared on unmount.", "aria-live announces success."],
    qa: ["Works over HTTPS and localhost.", "Graceful when clipboard is blocked.", "Screen reader announces 'Copied'."],
    aiMistakes: ["No error handling when clipboard write rejects.", "Leaving the timeout uncleared on unmount.", "No accessible announcement."],
    related: ["magnetic-primary-cta", "qa-empty-states"],
  },
  {
    slug: "ai-saas-hero-bento",
    title: "AI SaaS Hero + Feature Bento",
    description: "A converting hero (clear promise, two CTAs, product peek) flowing into an asymmetric bento of living feature tiles.",
    category: "saas-landing",
    difficulty: "Intermediate",
    tags: ["hero", "bento", "conversion"],
    featured: true,
    updatedAt: "2026-06-16",
    bestFor: "AI SaaS landing pages that need to state a promise and show the product in one screen.",
    avoidWhen: "Pre-product or no clear single promise — a bento of vague features amplifies the lack of focus.",
    whyItWorks: "A promise-led hero answers 'what changes for me?' instantly; the bento lets each feature breathe and earn a glance without a wall of text.",
    uxPrinciple: "One promise above the fold, evidence below. Lead with outcome, support with proof.",
    motionPrinciple: "Sequence the hero (fade+rise) on load; stagger bento tiles on scroll-in; give each tile one small living detail (counter, draw, toggle). Pause off-screen.",
    visualReference: "Headline + subhead + two buttons + a floating product shot, then a 6-tile asymmetric grid where each tile has a tiny self-contained animation.",
    prompts: {
      v0: "Build a Next.js + Tailwind + Motion AI SaaS hero: outcome headline, one-line subhead, primary + secondary CTA, and a floating product screenshot with a soft glow and slight cursor parallax. Below: an asymmetric bento of 6 feature tiles, each with one micro-animation (count-up, line-draw, toggle). Stagger tiles on scroll-in; pause off-screen. 60fps, reduced-motion aware.",
      agent: "Implement a Hero section (promise headline, subhead, two CTAs, parallax product image) and a Bento section: a CSS grid with varied tile sizes, each tile a small typed component with its own in-view micro-interaction. Use IntersectionObserver to start/stop animations. Keep sections composable.",
      scaffold: "Create an AI SaaS landing hero with a strong outcome headline, two buttons, and a product screenshot, followed by a bento grid of features where each tile has a small lively animation.",
      figma: "Design an AI SaaS hero (outcome headline, subhead, primary/secondary CTA, product mockup) and a 6-tile asymmetric bento. Note one micro-interaction per tile.",
    },
    implementation: [
      "Lead the hero with the outcome, not the feature list.",
      "Two CTAs max: one primary, one low-commitment secondary.",
      "Bento tiles vary in size; one living detail each; pause off-screen.",
      "Sequence hero entrance on load; stagger bento on scroll-in.",
    ],
    qa: ["Above-the-fold promise is legible in 3 seconds.", "Bento animations pause when not visible.", "Mobile stacks the bento sensibly.", "Reduced-motion shows final states."],
    aiMistakes: ["Feature-list headline instead of an outcome.", "Equal-size bento tiles (no hierarchy).", "All tiles animating at once, on a timer, even off-screen."],
    related: ["pricing-with-anchor", "aurora-mesh-background"],
  },
  {
    slug: "pricing-with-anchor",
    title: "Pricing with a Confident Anchor",
    description: "A three-tier table that uses anchoring and a single highlighted plan to make the choice obvious.",
    category: "saas-landing",
    difficulty: "Starter",
    tags: ["pricing", "conversion", "anchoring"],
    updatedAt: "2026-06-14",
    bestFor: "Any paid product with 2–4 plans.",
    avoidWhen: "You have one plan — then it's a single confident card, not a table.",
    whyItWorks: "Anchoring against a higher tier makes the target plan feel reasonable; one highlighted plan removes decision paralysis.",
    uxPrinciple: "Reduce choices to a recommendation. Guide, don't dump options.",
    visualReference: "Three cards, the middle one elevated and accented as 'Most popular,' with a clear feature ladder.",
    prompts: {
      v0: "Build a Next.js + Tailwind pricing section: three tiers, the recommended one elevated with an accent border and 'Most popular' badge. Clear feature ladder, annual/monthly toggle with a savings note, one primary CTA per card. Accessible, responsive, reduced-motion-friendly.",
      agent: "Create a typed Pricing component driven by a tiers array (name, price, features, highlight, cta). Render a billing toggle that recomputes prices. Highlight the recommended tier; ensure keyboard accessibility and a sensible mobile stack.",
      scaffold: "Make a 3-tier pricing section with a highlighted recommended plan and a monthly/annual toggle that shows the savings.",
      figma: "Design a 3-tier pricing table with the middle plan emphasized, a billing toggle, and a clear feature comparison.",
    },
    implementation: ["Drive tiers from data, not hardcoded markup.", "Elevate exactly one plan.", "Billing toggle recomputes and shows savings."],
    qa: ["Recommended plan is unmistakable.", "Toggle updates all prices.", "Mobile stacks without losing the highlight."],
    aiMistakes: ["Highlighting zero or multiple plans.", "Burying the price below the fold.", "No annual savings cue."],
    related: ["ai-saas-hero-bento", "magnetic-primary-cta"],
  },
  {
    slug: "dashboard-hierarchy-grid",
    title: "Dashboard with Real Hierarchy",
    description: "A dense dashboard that still reads at a glance: one hero metric, supporting cards, calm charts, scannable tables.",
    category: "dashboards",
    difficulty: "Advanced",
    tags: ["dashboard", "data-density", "hierarchy"],
    updatedAt: "2026-06-15",
    bestFor: "Analytics, admin, and ops surfaces where users return daily.",
    avoidWhen: "A marketing page — dashboards optimize for repeat scanning, not first impressions.",
    whyItWorks: "A single hero metric answers 'how are we doing?' instantly; everything else supports it. Hierarchy turns density into clarity.",
    uxPrinciple: "One primary number, then progressive detail. Density is fine if hierarchy is ruthless.",
    motionPrinciple: "Charts draw once on load (not on every re-render); numbers count up on first view; transitions between ranges crossfade rather than jump.",
    visualReference: "A top hero stat with a sparkline, a row of supporting KPI cards, a calm line chart, and a clean table with hover rows.",
    prompts: {
      v0: "Build a Next.js + Tailwind dashboard: a hero metric with a sparkline and trend, a row of 3–4 supporting KPI cards, one calm line chart, and a scannable table with hover rows and a quiet zebra. Strict type scale, generous spacing, one accent for positive trend. Charts draw on first view only. Reduced-motion safe.",
      agent: "Implement a Dashboard layout with a clear visual hierarchy: a HeroMetric (big number + sparkline + delta), KpiCard grid, a Chart that animates its draw once via in-view, and a Table with semantic markup and hover affordances. Keep components typed and data-driven; memoize chart data.",
      scaffold: "Create a clean SaaS dashboard with one big headline metric, a few supporting stat cards, a line chart, and a tidy data table. Calm, scannable, not cluttered.",
      figma: "Design a dashboard with a hero KPI, supporting cards, one chart, and a table. Establish a strict type scale and spacing system.",
    },
    implementation: [
      "Pick one hero metric; demote the rest to supporting cards.",
      "Draw charts once on first view; don't re-animate on every render.",
      "Use a strict type scale so density stays scannable.",
      "Tables: semantic <table>, hover rows, right-aligned numerics.",
    ],
    qa: ["The most important number is obvious within 1 second.", "Charts don't re-animate on unrelated state changes.", "Table is keyboard and screen-reader navigable.", "Numbers are tabular-aligned."],
    aiMistakes: ["Equal-weight cards everywhere (no hero).", "Re-animating charts on every render.", "Center-aligned numeric columns.", "Color used decoratively instead of for meaning."],
    related: ["ai-saas-hero-bento", "command-palette-pattern"],
  },
  {
    slug: "activation-onboarding-checklist",
    title: "Activation Onboarding Checklist",
    description: "A first-run checklist that drives users to their aha moment fast, with progress that rewards completion.",
    category: "onboarding",
    difficulty: "Intermediate",
    tags: ["onboarding", "activation", "empty-state"],
    featured: true,
    updatedAt: "2026-06-16",
    bestFor: "Products where value requires 2–4 setup steps before the aha moment.",
    avoidWhen: "Single-action products — a checklist adds friction where none is needed.",
    whyItWorks: "A visible, finite list with progress leverages the Zeigarnik effect: users want to complete what's started, and each step is a small win toward value.",
    uxPrinciple: "Make the path to value explicit and finite. The first run is your real homepage.",
    motionPrinciple: "Check-off animates with a satisfying spring; the progress bar fills smoothly; completing the last item triggers a brief celebratory moment.",
    visualReference: "A welcoming empty state with a 3–4 item checklist, a progress bar, and one obvious next action highlighted.",
    prompts: {
      v0: "Build a Next.js + Tailwind + Motion onboarding checklist: a friendly empty state with 3–4 steps, a progress bar, each step with a clear CTA. Completing a step animates a check with a spring and advances the bar; finishing all triggers a brief confetti/celebration. Persist progress. Reduced-motion safe.",
      agent: "Implement an OnboardingChecklist: typed steps with completion state persisted (localStorage now, API later), a progress indicator, spring check-off animations, and a completion celebration. Highlight the single next action. Keep it accessible (list semantics, focus management).",
      scaffold: "Create a first-run onboarding screen with a short checklist, a progress bar, and a clear next step. Celebrate when the user finishes all steps.",
      figma: "Design an onboarding empty state with a 3–4 step checklist, progress bar, highlighted next action, and a completion celebration state.",
    },
    implementation: ["Keep it to 3–4 steps that end at the aha moment.", "Highlight exactly one next action.", "Persist progress so it survives reload.", "Celebrate completion briefly."],
    qa: ["Progress survives a page reload.", "Only one next action is emphasized.", "Reduced-motion still confirms completion clearly.", "Screen readers announce step completion."],
    aiMistakes: ["Too many steps, or steps that don't lead to value.", "No persistence — progress resets on reload.", "Highlighting every step equally."],
    related: ["qa-empty-states", "ai-saas-hero-bento"],
  },
  {
    slug: "command-palette-pattern",
    title: "Command Palette (⌘K)",
    description: "A keyboard-first command surface that animates suggestions — the power-user UI users now expect in AI apps.",
    category: "agent-ui",
    difficulty: "Advanced",
    tags: ["cmdk", "keyboard", "agent"],
    featured: true,
    updatedAt: "2026-06-16",
    bestFor: "AI products, dev tools, and any app with many actions or content to navigate.",
    avoidWhen: "Simple consumer apps with 2–3 actions — a palette is overkill and undiscoverable for casual users.",
    whyItWorks: "It collapses navigation and actions into one fast, searchable surface, signaling 'this is a serious tool' to power users.",
    uxPrinciple: "Keyboard-first, mouse-optional. Fuzzy search plus clear grouping makes everything reachable in two keystrokes.",
    motionPrinciple: "Rows filter and reorder with a layout spring; the active row has an animated indicator; opening blurs the backdrop. Keep it snappy, not floaty.",
    visualReference: "A ⌘K modal with a search input and grouped, animated result rows; arrow keys move a highlighted selection.",
    prompts: {
      v0: "Build a Next.js + Motion command palette (⌘K): a blurred-backdrop modal with a search input and grouped result rows that filter and reorder with a layout spring. Arrow keys move selection (aria-activedescendant), Enter triggers, Esc closes. Highlight matched substrings. Fully keyboard accessible. Reduced-motion: instant filtering.",
      agent: "Implement a CommandPalette with cmdk-style behavior: global ⌘K shortcut, fuzzy search over a typed actions list, grouped results, keyboard navigation with aria-activedescendant, Motion layout animations on reorder, and focus trapping. Modular: actions provided via props/registry.",
      scaffold: "Add a ⌘K command palette that lets users search and run actions or jump to pages, with smooth animated results and full keyboard control.",
      figma: "Design a command palette modal: search field, grouped results, highlighted selection, empty state. Note keyboard navigation and the reorder animation.",
    },
    implementation: [
      "Global ⌘K / Ctrl+K listener; trap focus while open.",
      "Fuzzy-match and group results; highlight matched substrings.",
      "Arrow-key selection with aria-activedescendant; Enter to run; Esc to close.",
      "Animate reorder with layout springs; keep timing snappy.",
    ],
    qa: ["Fully operable by keyboard alone.", "Focus returns to the trigger on close.", "Empty state when no results.", "Reduced-motion disables reorder animation but keeps filtering."],
    aiMistakes: ["Mouse-only implementation with no keyboard nav.", "No focus trap or focus restore.", "Floaty, slow animations that hurt the power-user feel.", "Missing empty state."],
    related: ["dashboard-hierarchy-grid", "shared-element-route-morph"],
  },
  {
    slug: "spotlight-dark-hero-pattern",
    title: "Cursor-Spotlight Dark Hero",
    description: "A near-black hero where a soft light follows the cursor, revealing gradient type and a grid — premium and mysterious.",
    category: "spatial-3d",
    difficulty: "Intermediate",
    tags: ["spotlight", "dark", "depth"],
    updatedAt: "2026-06-15",
    bestFor: "Premium, dark-brand products and launches that want a sense of depth and discovery.",
    avoidWhen: "Content-heavy or accessibility-critical pages — low-contrast reveal can hurt readability.",
    whyItWorks: "Interactive light creates depth and invites exploration; the reveal mechanic makes the visitor an active participant, extending dwell time.",
    uxPrinciple: "Reward curiosity, but keep the essential message readable even without interaction.",
    motionPrinciple: "A radial mask follows the cursor with lerp smoothing; on touch it slowly auto-orbits so it's never dead. Keep the CTA legible regardless of light position.",
    visualReference: "A dark canvas with a faint dotted grid and gradient headline that brightens under a soft moving light.",
    prompts: {
      v0: "Build a Next.js + Tailwind dark hero (#0a0a0a): a soft radial spotlight follows the cursor via a CSS mask, revealing a faint dotted grid and a gradient headline that's dim outside the light. CTA stays legible everywhere and glows under the light. Touch: slow auto-orbit. Reduced-motion: static dim reveal. 60fps.",
      agent: "Implement a SpotlightHero client component: track pointer, lerp a CSS custom property for the mask position, render a dotted-grid layer and gradient headline masked by a radial gradient. Auto-orbit on touch via rAF. Ensure the CTA meets contrast regardless of spotlight position. Reduced-motion fallback.",
      scaffold: "Create a dark hero where a soft light follows the mouse and reveals the headline and a subtle grid. Keep the main button readable at all times.",
      figma: "Design a dark spotlight hero: dim gradient headline, dotted grid, a soft light reveal. Note the cursor-follow interaction and a static fallback.",
    },
    implementation: ["Lerp the mask position for smoothness.", "Auto-orbit on touch so it's never static.", "Guarantee CTA contrast regardless of light position.", "Keep the essential headline readable without interaction."],
    qa: ["CTA is legible with the light anywhere.", "Touch devices show motion (auto-orbit).", "Reduced-motion shows a static, readable reveal.", "60fps on mid-range hardware."],
    aiMistakes: ["Making the headline unreadable when the light isn't over it.", "No touch fallback (dead on mobile).", "Heavy per-frame work causing jank."],
    related: ["aurora-mesh-background", "ai-saas-hero-bento"],
  },
  {
    slug: "motion-logo-system",
    title: "Motion Logo & Brand Mark",
    description: "A wordmark with a small, repeatable motion signature that makes an AI product feel like a real brand.",
    category: "brand-systems",
    difficulty: "Intermediate",
    tags: ["brand", "logo", "identity"],
    updatedAt: "2026-06-14",
    bestFor: "Launches, loaders, and nav marks where a tiny consistent motion builds recognition.",
    avoidWhen: "It loops distractingly in the nav — a brand mark should animate on entrance, then rest.",
    whyItWorks: "A consistent motion signature is memorable and signals craft. Repeated across loader, nav, and OG, it compounds into recognition.",
    uxPrinciple: "Consistency over spectacle. The same small move everywhere beats a different flourish each time.",
    motionPrinciple: "One signature move (a draw-on, a particle assemble, a mark that completes) used on load and reused at smaller scale in the nav. Animate once, then settle.",
    visualReference: "A wordmark that draws or assembles on first load, then sits still; the same mark gives a subtle nod on nav hover.",
    prompts: {
      v0: "Build a Next.js + Motion brand mark: an SVG wordmark that draws its strokes on first load (pathLength) then rests. Reuse a smaller version in the nav with a subtle hover nod. Provide a static favicon/OG variant. Reduced-motion: render the final mark instantly.",
      agent: "Create a Logo component: animated SVG (stroke draw or assemble) on mount, a compact nav variant with a hover micro-motion, and a static export path for favicon/OG. Keep one motion signature shared across variants; respect reduced-motion.",
      scaffold: "Design a wordmark that animates in once on load (drawing itself) and a smaller calm version for the navbar. Keep the motion consistent.",
      figma: "Design a wordmark plus a motion signature spec: how it draws/assembles on load, the nav variant, and static favicon/OG marks.",
    },
    implementation: ["Define one signature move; reuse it across loader and nav.", "Animate on mount, then rest — no infinite nav loop.", "Provide static favicon/OG exports.", "Respect reduced-motion."],
    qa: ["Nav mark doesn't loop distractingly.", "Static favicon/OG exist.", "Reduced-motion shows the final mark instantly.", "Mark is legible at 16px."],
    aiMistakes: ["A different animation in every place (no signature).", "An infinite loop in the nav.", "No static fallback for favicon/OG."],
    related: ["spotlight-dark-hero-pattern", "ai-saas-hero-bento"],
  },
];

export function getPattern(slug: string): Pattern | undefined {
  return PATTERNS.find((p) => p.slug === slug);
}
export function patternsByCategory(categorySlug: string): Pattern[] {
  return PATTERNS.filter((p) => p.category === categorySlug);
}
