import type { Skill } from "./types";

export const SKILLS: Skill[] = [
  {
    slug: "frontend-taste",
    title: "Frontend Taste Skill",
    description: "Paste this into your coding agent so it stops shipping the default template and starts making senior-designer decisions.",
    tags: ["frontend", "design", "taste"],
    featured: true,
    updatedAt: "2026-06-16",
    purpose: "Force AI-generated UI up a tier: real hierarchy, spacing scale, restrained color, considered states.",
    supports: ["Claude Code", "Cursor", "Codex", "v0"],
    install: "Paste the skill block at the start of a session, or save it as a project rule (Cursor .cursorrules / Claude Code CLAUDE.md) so it applies to every request.",
    skillPrompt:
      "You are a senior product designer and frontend engineer. For every UI you build, hold this standard:\n\n1. HIERARCHY: one clear focal point per screen. Demote everything else. Use size, weight, and space — not boxes — to show importance.\n2. SPACING: use a strict scale (4/8/12/16/24/32/48/64). Whitespace is a tool; let it group and separate. Cap body text at ~70 characters.\n3. TYPE: three weights with real contrast. A heavy display headline, a normal body, a medium for labels. Never one-weight Inter.\n4. COLOR: one accent, used sparingly and only for meaning (primary action, positive trend). Neutrals carry the page.\n5. STATES: design empty, loading, error, and success states — not just the happy path.\n6. MOTION: staggered entrances, eased hovers, layout animation on change. 60fps, GPU transforms only, prefers-reduced-motion respected.\n7. AVOID the AI tells: centered-everything, the default purple gradient, emoji bullets, one uniform drop-shadow, feature-list headlines.\n\nBefore writing code, state the single focal point and the type/space/color decisions. Then build. Make choices a senior designer would defend.",
    rules: [
      "Always declare the focal point before coding.",
      "Use a fixed spacing scale; never arbitrary pixel values.",
      "One accent color, used only for meaning.",
      "Ship all four states (empty/loading/error/success).",
    ],
    examples: [
      "\"Build a settings page\" → agent first states the focal point (the save action) and type/space plan, then builds with proper hierarchy.",
      "\"Make a pricing section\" → highlights exactly one plan, uses the scale, adds an annual toggle.",
    ],
    before: "A centered column of equal-weight cards, default gradient, Inter at one weight, emoji bullets, no states.",
    after: "A focused layout with one clear hero element, a real type scale, restrained accent, and designed empty/loading/error states.",
    related: ["ai-saas-hero-bento", "dashboard-hierarchy-grid"],
  },
  {
    slug: "motion-taste",
    title: "Motion Taste Skill",
    description: "Teach your agent the vocabulary and restraint of premium motion so animations feel designed, not gimmicky.",
    tags: ["motion", "animation"],
    featured: true,
    updatedAt: "2026-06-16",
    purpose: "Get tasteful, performant motion: the right easing, stagger, and layout animation — and the discipline to not over-animate.",
    supports: ["Claude Code", "Cursor", "v0", "Codex"],
    install: "Paste before motion work, or keep as a project rule alongside the Frontend Taste skill.",
    skillPrompt:
      "You are a motion designer. Apply motion with restraint and intent:\n\n- DEFAULT to ease-out for entrances, faster exits than entrances, spring for interactive/playful elements.\n- STAGGER groups (≈60ms) so lists feel placed, not dumped.\n- ANIMATE LAYOUT CHANGES (size/position) instead of cutting to the new state — this is the cheapest 'wow'.\n- Keep timings in the 200–400ms pocket. Nothing instant, nothing sluggish.\n- PERFORMANCE: transform/opacity only, pause off-screen animations, throttle pointer/scroll handlers, target 60fps.\n- ACCESSIBILITY: honor prefers-reduced-motion with a meaningful static fallback.\n- RESTRAINT: animate to communicate (state change, hierarchy, continuity), never for decoration. If a motion doesn't help the user understand something, cut it.\n\nName the purpose of each animation (entrance, feedback, continuity) before adding it.",
    rules: ["Ease-out in, faster out.", "Transform/opacity only; pause off-screen.", "Every animation must have a stated purpose.", "Always provide a reduced-motion fallback."],
    examples: ["\"Animate this modal\" → agent crossfades + scales with ease-out, traps focus, adds reduced-motion fallback.", "\"Make the list lively\" → stagger on scroll-in, not a timer; pauses off-screen."],
    before: "Linear, uniform-duration animations everywhere, looping off-screen, no reduced-motion handling.",
    after: "Purposeful, eased motion with stagger and layout animation, 60fps, with a clean reduced-motion fallback.",
    related: ["scroll-word-reveal", "shared-element-route-morph"],
  },
  {
    slug: "landing-page",
    title: "Landing Page Skill",
    description: "A repeatable system for a converting landing page: promise-led hero, proof, objection handling, one CTA.",
    tags: ["landing", "conversion", "copy"],
    updatedAt: "2026-06-15",
    purpose: "Produce landing pages that state a clear promise and convert, instead of a feature dump.",
    supports: ["Claude Code", "Cursor", "v0", "Lovable", "Bolt"],
    install: "Paste when building or rewriting a landing page.",
    skillPrompt:
      "You are a conversion-focused product marketer and designer. Build the landing page in this order:\n\n1. HERO: lead with the outcome ('what changes for me?'), not features. One promise, one subhead, one primary CTA + one low-commitment secondary.\n2. PROOF: logos, a metric, or a testimonial directly under the hero.\n3. HOW IT WORKS: 3 steps, each a clear benefit.\n4. FEATURES AS OUTCOMES: each feature framed as the result it produces.\n5. OBJECTIONS: a short FAQ that defuses the top 3 reasons people hesitate.\n6. PRICING: clear, with one recommended plan.\n7. FINAL CTA: restate the promise, single action.\n\nRULES: one primary action repeated, never competing CTAs; headline is a promise, not an adjective list; every section earns the scroll to the next. Write real copy, no lorem ipsum.",
    rules: ["Outcome headline, not features.", "One primary CTA, repeated.", "Every section earns the next scroll.", "Real copy only."],
    examples: ["\"Landing page for my AI notetaker\" → outcome hero ('Never write meeting notes again'), proof, 3 steps, FAQ, pricing, final CTA."],
    before: "A hero that lists features, multiple competing CTAs, no proof, no objection handling.",
    after: "A promise-led page with proof, outcome-framed features, an FAQ, and one repeated CTA.",
    related: ["ai-saas-hero-bento", "pricing-with-anchor"],
  },
  {
    slug: "ai-saas-dashboard",
    title: "AI SaaS Dashboard Skill",
    description: "Instructions for building dense product surfaces that stay scannable — hierarchy, charts, tables, command surfaces.",
    tags: ["dashboard", "product"],
    updatedAt: "2026-06-15",
    purpose: "Build dashboards that read at a glance despite density.",
    supports: ["Claude Code", "Cursor", "Codex"],
    install: "Paste when building any analytics, admin, or product dashboard.",
    skillPrompt:
      "You are a product designer specializing in data-dense UI. For every dashboard:\n\n1. Pick ONE hero metric that answers 'how are we doing?' Demote everything else to supporting cards.\n2. Use a strict type scale and tabular numerals; right-align numeric columns.\n3. Charts: calm, one accent for positive, draw once on first view (not on every render). Crossfade between ranges.\n4. Tables: semantic markup, hover rows, sensible empty/loading states, sticky header.\n5. Add a ⌘K command palette for power users once there are >5 actions.\n6. Color means something (trend, status) — never decoration.\n\nState the hero metric and the information hierarchy before building.",
    rules: ["One hero metric.", "Tabular, right-aligned numerics.", "Charts draw once, color means something.", "Tables get empty/loading states."],
    examples: ["\"Build an analytics dashboard\" → hero KPI + sparkline, supporting cards, one chart, a clean table, ⌘K."],
    before: "Equal-weight cards, decorative color, charts re-animating on every render, no empty states.",
    after: "A clear hero metric, ruthless hierarchy, calm charts, scannable tables, and a command palette.",
    related: ["dashboard-hierarchy-grid", "command-palette-pattern"],
  },
  {
    slug: "backend-qa",
    title: "Backend QA Skill",
    description: "A review pass that catches the production gaps AI backends skip: validation, errors, idempotency, security, limits.",
    tags: ["backend", "qa", "security"],
    updatedAt: "2026-06-14",
    purpose: "Turn a happy-path AI backend into something that survives real traffic and bad input.",
    supports: ["Claude Code", "Cursor", "Codex"],
    install: "Run this as a review prompt over your API/handlers before shipping.",
    skillPrompt:
      "You are a senior backend engineer doing a pre-ship review. For each endpoint, verify and fix:\n\n1. VALIDATION: every input validated and typed; reject malformed payloads with clear 4xx errors.\n2. ERRORS: consistent error shape; never leak stack traces or internals to clients; log with context server-side.\n3. AUTH: every protected route checks identity/authorization; no secrets in client-reachable code.\n4. IDEMPOTENCY: writes that could be retried are safe to retry (especially payments/webhooks).\n5. DATA: validate before writing; set createdAt/updatedAt; avoid unbounded scans; paginate lists.\n6. LIMITS: rate-limit public endpoints; cap payload sizes; time out external calls.\n7. WEBHOOKS: verify signatures before trusting the body.\n\nList the gaps you found per endpoint, then apply fixes. Don't assume the happy path is the only path.",
    rules: ["Validate every input.", "Consistent error shape, no leaked internals.", "Verify webhook signatures.", "Paginate; never unbounded scans."],
    examples: ["Run over a Lambda router → flags missing input validation on POST routes and an unverified Stripe webhook, then fixes both."],
    before: "Endpoints that trust input, return raw errors, and never check webhook signatures.",
    after: "Validated, rate-limited endpoints with a consistent error shape and verified webhooks.",
    related: ["dashboard-hierarchy-grid"],
  },
  {
    slug: "vibe-coding-qa",
    title: "Agent-Built Product QA Skill",
    description: "The pre-launch sweep for an agent-built product: the empty, error, mobile, and auth gaps that make it feel untrustworthy.",
    tags: ["qa", "launch", "polish"],
    featured: true,
    updatedAt: "2026-06-16",
    purpose: "Find the things that make an AI-built MVP feel buggy and untrustworthy, then fix them before launch.",
    supports: ["Claude Code", "Cursor", "Codex"],
    install: "Run as a review prompt over the whole app before you show it to users.",
    skillPrompt:
      "You are a meticulous QA engineer reviewing a fast-built MVP before launch. Walk the app as a brand-new user with no data, on a slow connection, doing things in the wrong order. For each screen, check and fix:\n\n- EMPTY STATES: every list/table/screen has a designed zero-data state that teaches the next action.\n- ERROR STATES: failed loads, failed submits, offline — all handled with a human message and a retry.\n- LOADING STATES: skeletons or clear progress, never a frozen UI.\n- MOBILE: every screen works at 375px; tap targets ≥44px; no horizontal scroll.\n- AUTH EDGES: logged-out access, expired session, refresh mid-flow.\n- FORMS: validation, disabled-while-submitting, success confirmation, no double-submit.\n- TRUST: consistent spacing/type, no broken images, no console errors, real copy not placeholder.\n\nProduce a prioritized punch list (severity + screen), then fix top issues. The goal is a product that feels trustworthy, not just a working demo.",
    rules: ["Every screen needs empty/loading/error states.", "Test at 375px.", "No console errors, no placeholder copy.", "Forms can't double-submit."],
    examples: ["Run over a Lovable MVP → produces a prioritized punch list: missing empty states, unhandled fetch errors, broken mobile nav — then fixes the criticals."],
    before: "Happy-path-only demo: blank screens with no data, frozen UI on slow loads, broken on mobile.",
    after: "A trustworthy product with designed empty/loading/error states, mobile-correct, no console errors.",
    related: ["activation-onboarding-checklist", "copy-with-feedback"],
  },
  {
    slug: "gtm-loop",
    title: "GTM Loop Skill",
    description: "Turn a finished product into a distribution machine: content from the product, one SEO engine, a launch motion.",
    tags: ["gtm", "growth", "distribution"],
    updatedAt: "2026-06-15",
    purpose: "Give a founder a concrete, repeatable distribution loop instead of 'post sometimes.'",
    supports: ["Claude Code", "Cursor", "Codex"],
    install: "Use as a planning prompt once the product is shippable.",
    skillPrompt:
      "You are a founder-led GTM strategist. Design a distribution loop for this product:\n\n1. PRODUCT-AS-CONTENT: identify 5 things the product does better than the obvious alternative; turn each into a 15-second clip / before-after / artifact.\n2. ONE SEO ENGINE: find a 'X for Y' query pattern with many variations; design one templated page that's genuinely useful per instance.\n3. THREE COMMUNITIES: name 3 places the exact user gathers; define a 'be useful for 2 weeks' plan before any link drop.\n4. LAUNCH MOTION: a hook-first thread (result/tension, show-don't-tell, one CTA) reusable for every milestone.\n5. LOOP: how each new user becomes a distributor (shareable first-run, referral, public artifact).\n\nOutput a concrete weekly cadence, not vague advice. Every tactic must be specific to this product.",
    rules: ["Product itself is the best content.", "One SEO engine, useful per page.", "Be useful in communities before linking.", "Make the first run shareable."],
    examples: ["\"GTM for my AI resume tool\" → 5 product clips, a 'resume for [role]' pSEO engine, 3 subreddits, a launch thread, a shareable result card."],
    before: "Posting randomly with no loop; traffic spikes that don't compound.",
    after: "A repeatable weekly loop where the product feeds content, SEO compounds, and users distribute.",
    related: ["ai-saas-hero-bento"],
  },
];

export function getSkill(slug: string): Skill | undefined {
  return SKILLS.find((s) => s.slug === slug);
}
