import type { Teardown } from "./types";

/** Principle-based teardowns. We describe archetypes and lessons, not copied assets. */
export const TEARDOWNS: Teardown[] = [
  {
    slug: "best-in-class-issue-tracker",
    title: "The Best-in-Class Issue Tracker",
    reference: "Archetype: a keyboard-first developer issue tracker",
    description: "Why the fastest project tools feel fast: keyboard-first flow, instant optimistic updates, and ruthless visual restraint.",
    tags: ["productivity", "speed", "keyboard"],
    featured: true,
    updatedAt: "2026-06-16",
    whatsGood: ["Every action has a keyboard path; the mouse is optional.", "Optimistic UI — actions feel instant, reconciliation is invisible.", "Monochrome restraint so status colors actually mean something.", "A command palette unifies navigation and actions."],
    uxLesson: "Speed is a feeling built from keyboard access + optimistic updates. Remove every modal and confirmation that isn't load-bearing.",
    motionLesson: "Motion is near-invisible and purposeful: layout animations on reorder, nothing decorative. Restraint reads as confidence.",
    productLesson: "Opinionated defaults beat configuration. The tool decides, so the user doesn't have to — and onboarding is trivial.",
    recreatePrompt: "Build a keyboard-first task list: ⌘K command palette, optimistic add/complete (UI updates instantly, syncs after), monochrome palette with one status accent, layout animations on reorder. No modals for common actions.",
    adaptSafely: "Adopt the keyboard-first + optimistic-UI principles; design your own visual language. Don't copy the exact look — copy the *feel* of speed.",
    aiMistakes: ["Adding confirmation modals to every action (kills the speed).", "Decorative color that drowns out status meaning.", "No keyboard paths — mouse-only."],
  },
  {
    slug: "premium-fintech-dashboard",
    title: "The Premium Fintech Dashboard",
    reference: "Archetype: a consumer finance / money dashboard",
    description: "How calm money apps build trust: one honest number, generous space, and motion that reassures rather than excites.",
    tags: ["fintech", "trust", "dashboard"],
    updatedAt: "2026-06-15",
    whatsGood: ["One hero number (balance/net worth) answers the main question instantly.", "Generous whitespace signals safety and seriousness.", "Numbers count up calmly; nothing flashes or gamifies money.", "Clear, boring error/edge states — trust over delight here."],
    uxLesson: "For money, calm is the feature. Reduce dopamine, increase clarity. The user should feel in control, not stimulated.",
    motionLesson: "Slow, weighty motion. A gentle count-up on the hero number; no springy bounce on financial figures.",
    productLesson: "Trust is the product. Honest framing, clear states, and no dark patterns matter more than feature count.",
    recreatePrompt: "Build a finance dashboard with one large hero balance (calm count-up), a restrained palette, generous spacing, a simple trend chart, and explicit, plain error/empty states. No gamification, no flashy motion.",
    adaptSafely: "Borrow the calm + one-hero-number principle for any high-stakes data. Keep your own brand; don't mimic a specific bank's UI.",
    aiMistakes: ["Gamifying money with confetti and streaks.", "Burying the main number in a grid of equal cards.", "Springy/bouncy motion on financial figures (feels untrustworthy)."],
  },
  {
    slug: "ai-chat-product",
    title: "The Trustworthy AI Chat Product",
    reference: "Archetype: a production AI assistant interface",
    description: "What separates a credible AI product from a toy: streaming done right, visible reasoning, citations, and graceful failure.",
    tags: ["ai", "agent", "chat"],
    featured: true,
    updatedAt: "2026-06-16",
    whatsGood: ["Tokens stream smoothly with a stable layout (no jank as text grows).", "Tool-calls and sources are visible, building trust in the output.", "Clear states for thinking, streaming, error, and stopped.", "A persistent input that never blocks; stop/regenerate always available."],
    uxLesson: "Show the work. Visible reasoning, tool-calls, and citations turn a black box into something users trust and verify.",
    motionLesson: "Streaming text needs a stable container and a calm caret — no layout shift, no bouncing as content grows.",
    productLesson: "Graceful failure is a feature. Timeouts, rate limits, and refusals need human messaging and a clear next step.",
    recreatePrompt: "Build an AI chat UI with smooth token streaming in a layout-stable container, visible tool-call/citation chips, distinct thinking/streaming/error/stopped states, and an always-available stop/regenerate. Handle timeouts and rate limits with human copy.",
    adaptSafely: "Adopt the transparency + graceful-failure principles. Design your own chrome; the trust comes from showing work, not the look.",
    aiMistakes: ["Layout that jumps as tokens stream.", "Hiding tool-calls/sources (black box).", "No handling for timeouts, refusals, or rate limits."],
  },
  {
    slug: "developer-docs-site",
    title: "The Reference Developer Docs",
    reference: "Archetype: best-in-class API documentation",
    description: "Why great docs convert developers: instant search, copy-everything, runnable examples, and merciless information scent.",
    tags: ["docs", "developer", "content"],
    updatedAt: "2026-06-14",
    whatsGood: ["Instant ⌘K search with great information scent.", "Every snippet is copyable; examples are runnable.", "A persistent, scannable left nav with clear hierarchy.", "Code and prose share one calm, readable type system."],
    uxLesson: "Docs are a product. Search, copy, and runnable examples reduce time-to-success, which is the real conversion metric.",
    motionLesson: "Almost none — and that's right. Docs reward stability and speed over flourish.",
    productLesson: "Time-to-first-success sells developer tools. Optimize the docs path like an onboarding funnel.",
    recreatePrompt: "Build a docs layout: ⌘K instant search, a scannable left nav, copy buttons on every code block, runnable examples, and one calm type system shared by code and prose. Optimize for time-to-first-success.",
    adaptSafely: "Treat your docs as onboarding. Copy the search + copy + runnable principles, not a specific company's theme.",
    aiMistakes: ["Search that's slow or absent.", "Non-copyable code blocks.", "Decorative motion that slows navigation."],
  },
  {
    slug: "consumer-onboarding-flow",
    title: "The Sticky Consumer Onboarding",
    reference: "Archetype: a habit-forming consumer app's first run",
    description: "How the best first-runs hit the aha moment fast — ask less, show value sooner, and make progress feel rewarding.",
    tags: ["onboarding", "activation", "consumer"],
    updatedAt: "2026-06-15",
    whatsGood: ["Value before signup where possible — show the magic, then ask.", "Each step is a small win with visible progress.", "Defaults and smart guesses reduce typing to near-zero.", "A celebratory completion moment that earns the next session."],
    uxLesson: "Defer friction. Every field you remove and every value you show earlier increases activation.",
    motionLesson: "Satisfying check-offs and a smooth progress bar leverage the desire to complete what's started.",
    productLesson: "Activation, not signups, is the metric. Design the first run as your real homepage.",
    recreatePrompt: "Build a first-run flow that shows value before asking for much: a 3-step checklist with visible progress, smart defaults, spring check-offs, and a brief celebration at completion. Minimize required input.",
    adaptSafely: "Borrow 'show value before friction' and the finite-checklist principle. Fit your product's real aha moment.",
    aiMistakes: ["Long forms before any value is shown.", "No progress indication.", "An onboarding that doesn't end at the actual aha moment."],
  },
  {
    slug: "editorial-marketing-site",
    title: "The Editorial Marketing Site",
    reference: "Archetype: an award-grade product marketing site",
    description: "What makes a marketing site feel expensive: editorial typography, scroll choreography with restraint, and a strong point of view.",
    tags: ["marketing", "editorial", "brand"],
    updatedAt: "2026-06-14",
    whatsGood: ["Big, confident editorial type carries the page.", "Scroll choreography is purposeful — one strong moment, not constant motion.", "A clear point of view in the copy, not feature soup.", "Whitespace and rhythm that feel composed, not filled."],
    uxLesson: "Confidence is a design choice. Big type, strong opinions, and restraint read as expensive.",
    motionLesson: "Pick one or two memorable scroll moments and let the rest be calm. Constant motion cheapens the effect.",
    productLesson: "A point of view differentiates. Say something; don't list everything.",
    recreatePrompt: "Build an editorial marketing page: oversized confident type, one or two purposeful scroll-choreographed moments, opinionated copy, and composed whitespace. Restraint over constant motion.",
    adaptSafely: "Adopt the editorial-type + restraint + POV principles. Develop your own voice and layout, not a clone.",
    aiMistakes: ["Animating every section (motion fatigue).", "Feature-list copy with no point of view.", "Timid, template-sized typography."],
  },
  {
    slug: "marketplace-listing",
    title: "The High-Trust Marketplace Listing",
    reference: "Archetype: a premium marketplace product/listing page",
    description: "How listings drive decisions without manipulation: honest trust signals, clear hierarchy, and no fake-urgency theater.",
    tags: ["marketplace", "commerce", "trust"],
    updatedAt: "2026-06-13",
    whatsGood: ["A clear visual hierarchy: image, price, decision factors, then detail.", "Honest trust signals (reviews, guarantees) without manipulation.", "The total cost is shown up front — no surprise fees at checkout.", "Calm, scannable choices rather than a wall of urgency banners."],
    uxLesson: "Trust converts better than pressure. Honest hierarchy and upfront totals beat fake-urgency dark patterns.",
    motionLesson: "Subtle hover elevation and smooth image transitions — nothing that distracts from the decision.",
    productLesson: "Sustainable conversion comes from trust. Dark patterns win once and churn forever.",
    recreatePrompt: "Build a marketplace listing: strong hierarchy (image, price, key decision factors, detail), honest trust signals, upfront total cost, calm hover/image transitions. No fake-urgency banners.",
    adaptSafely: "Use the trust-over-pressure and upfront-cost principles. Design your own listing layout.",
    aiMistakes: ["Fake urgency ('3 left!', fake countdowns).", "Hidden fees revealed at checkout.", "Cluttered banners burying the decision factors."],
  },
  {
    slug: "spatial-product-landing",
    title: "The Spatial Product Landing",
    reference: "Archetype: a hardware/3D product showcase",
    description: "How 3D landing pages stay impressive without tanking performance: scroll-tied camera, lazy WebGL, and a graceful fallback.",
    tags: ["3d", "spatial", "performance"],
    updatedAt: "2026-06-13",
    whatsGood: ["A 3D object whose motion is tied to scroll, so the user directs it.", "WebGL is lazy-loaded; mobile/low-power gets a beautiful static fallback.", "DPR capped and assets optimized so it holds 60fps.", "The 3D serves the story (showing the product), not just spectacle."],
    uxLesson: "Spectacle must earn its cost. 3D should explain the product, and degrade gracefully where it can't run well.",
    motionLesson: "Tie 3D to scroll so it's interactive and controllable; never autoplay a heavy scene the user can't influence.",
    productLesson: "Performance is UX. A gorgeous scene that stutters or drains battery loses more than it wins.",
    recreatePrompt: "Build a 3D product landing with React Three Fiber: scroll-tied camera/rotation, lazy-loaded canvas, capped DPR, optimized assets for 60fps, and a beautiful static poster fallback for mobile/low-power and reduced-motion.",
    adaptSafely: "Adopt scroll-tied + lazy + graceful-fallback principles. Only add 3D if it explains your product.",
    aiMistakes: ["Shipping heavy WebGL with no fallback (broken/slow on mobile).", "Autoplaying scenes the user can't control.", "Uncapped DPR and unoptimized assets (jank, battery drain)."],
  },
];

export function getTeardown(slug: string): Teardown | undefined {
  return TEARDOWNS.find((t) => t.slug === slug);
}
